// <auto-generated />
using Lab38Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Lab38Api.Migrations
{
    [DbContext(typeof(BirthdayPlanDbContext))]
    [Migration("20171102173613_BirthdayListID")]
    partial class BirthdayListID
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lab38Api.Models.Birthday", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("BirthdayList");
                });

            modelBuilder.Entity("Lab38Api.Models.BirthdayPlan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BirthdayID");

                    b.Property<bool>("IsComplete");

                    b.Property<string>("Task");

                    b.HasKey("ID");

                    b.HasIndex("BirthdayID");

                    b.ToTable("BirthdayPlan");
                });

            modelBuilder.Entity("Lab38Api.Models.BirthdayPlan", b =>
                {
                    b.HasOne("Lab38Api.Models.Birthday")
                        .WithMany("Tasks")
                        .HasForeignKey("BirthdayID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
